"""update wallet address fields

Revision ID: 3908772bf8db
Revises: 3789318f52c1
Create Date: 2026-10-09 12:01:20.616966

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3908772bf8db"
down_revision: str | None = "3789318f52c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_addresses", sa.Column("wallet_address", sa.String(length=512), nullable=False)
    )
    op.alter_column(
        "wallet_addresses",
        "rafiki_wallet_address_id",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "wallet_addresses",
        "asset_scale",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=8),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_wallet_addresses_address"), table_name="wallet_addresses")
    op.create_index(
        op.f("ix_wallet_addresses_wallet_address"),
        "wallet_addresses",
        ["wallet_address"],
        unique=True,
    )
    op.drop_column("wallet_addresses", "public_name")
    op.drop_column("wallet_addresses", "address")
    op.drop_column("wallet_addresses", "asset_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_addresses",
        sa.Column("asset_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "wallet_addresses",
        sa.Column("address", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    )
    op.add_column(
        "wallet_addresses",
        sa.Column("public_name", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_wallet_addresses_wallet_address"), table_name="wallet_addresses")
    op.create_index(
        op.f("ix_wallet_addresses_address"), "wallet_addresses", ["address"], unique=True
    )
    op.alter_column(
        "wallet_addresses",
        "asset_scale",
        existing_type=sa.String(length=8),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "wallet_addresses",
        "rafiki_wallet_address_id",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.drop_column("wallet_addresses", "wallet_address")
    # ### end Alembic commands ###
