"""wallet addresses

Revision ID: 3789318f52c1
Revises: f584a004f645
Create Date: 2026-10-07 16:37:47.656290

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3789318f52c1"
down_revision: str | None = "f584a004f645"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=False),
        sa.Column("public_name", sa.String(length=128), nullable=True),
        sa.Column("rafiki_wallet_address_id", sa.String(length=64), nullable=True),
        sa.Column("asset_id", sa.String(length=64), nullable=True),
        sa.Column("asset_code", sa.String(length=8), nullable=False),
        sa.Column("asset_scale", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_wallet_addresses_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_addresses")),
    )
    op.create_index(
        op.f("ix_wallet_addresses_address"), "wallet_addresses", ["address"], unique=True
    )
    op.create_index(
        op.f("ix_wallet_addresses_rafiki_wallet_address_id"),
        "wallet_addresses",
        ["rafiki_wallet_address_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wallet_addresses_user_id"), "wallet_addresses", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_addresses_user_id"), table_name="wallet_addresses")
    op.drop_index(
        op.f("ix_wallet_addresses_rafiki_wallet_address_id"), table_name="wallet_addresses"
    )
    op.drop_index(op.f("ix_wallet_addresses_address"), table_name="wallet_addresses")
    op.drop_table("wallet_addresses")
    # ### end Alembic commands ###
